# Generated by Django 6.0.1 on 2026-06-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('species', models.CharField(blank=True, default='', max_length=50)),
                ('livestock_type', models.CharField(blank=True, default='', max_length=100)),
                ('farm_location', models.CharField(blank=True, max_length=255, null=True)),
                ('health_status', models.CharField(default='Healthy', max_length=100)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('municipal_license_id', models.CharField(blank=True, max_length=100, null=True)),
                ('issuing_zone', models.CharField(blank=True, max_length=200, null=True)),
                ('is_municipally_verified', models.BooleanField(default=False)),
                ('municipal_verified_at', models.DateTimeField(blank=True, null=True)),
                ('ownership_verified', models.BooleanField(default=False)),
                ('ownership_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('health_status', models.CharField(default='Healthy', max_length=100)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('municipal_license_id', models.CharField(blank=True, max_length=100, null=True)),
                ('issuing_zone', models.CharField(blank=True, max_length=200, null=True)),
                ('is_municipally_verified', models.BooleanField(default=False)),
                ('municipal_verified_at', models.DateTimeField(blank=True, null=True)),
                ('ownership_verified', models.BooleanField(default=False)),
                ('ownership_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('rescue', 'Rescue Needed'), ('disease_report', 'Disease Sighted')], default='rescue', max_length=20)),
                ('animal_description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
