# Generated by Django 6.0.1 on 2026-04-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
