# Generated by Django 6.0.1 on 2026-06-06 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestock',
            name='is_municipally_verified',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='issuing_zone',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='municipal_license_id',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='municipal_verified_at',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='is_municipally_verified',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='issuing_zone',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='municipal_license_id',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='municipal_verified_at',
        ),
    ]
