# Generated by Django 6.0.1 on 2026-04-22 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_alter_pet_media_url'),
        ('shelter', '0003_animalinventory_listing_type_animalinventory_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='assigned_shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_missions', to='shelter.shelter'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
