# Generated by Django 6.0.1 on 2026-06-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0003_remove_livestock_is_municipally_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosalert',
            name='animal_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
