# Generated by Django 6.0.1 on 2026-05-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0003_sosalert_assigned_shelter_sosalert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='source_animal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
