# Generated by Django 6.0.1 on 2026-06-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0004_alter_sosalert_animal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='municipality',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
