# Generated by Django 6.0.1 on 2026-05-14 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0004_pet_source_animal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='source_animal_id',
        ),
    ]
