# Generated by Django 6.0.1 on 2026-05-22 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0005_remove_pet_source_animal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='citizens.pet')),
                ('livestock_type', models.CharField(max_length=100)),
                ('herd_size', models.PositiveIntegerField(default=1)),
                ('farm_location', models.TextField(blank=True, null=True)),
            ],
            bases=('citizens.pet',),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='alert_type',
            field=models.CharField(choices=[('rescue', 'Rescue Needed'), ('disease_report', 'Disease Sighted')], default='rescue', max_length=20),
        ),
    ]
