# Generated by Django 6.0.1 on 2026-05-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0006_livestock_sosalert_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_municipally_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='issuing_zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='municipal_license_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='municipal_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='ownership_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='ownership_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
