# Generated by Django 6.0.1 on 2026-06-06 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aicompatibilityscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aicompatibilityscore',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.animalinventory'),
        ),
        migrations.AddField(
            model_name='lifestyleassessment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_assessment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='analytics.pet'),
        ),
        migrations.AddField(
            model_name='healthriskflag',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.pet'),
        ),
    ]
