# Generated by Django 6.0.1 on 2026-06-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelteradminprofile',
            name='shelter_type',
            field=models.CharField(default='mixed', max_length=50),
        ),
        migrations.AddField(
            model_name='shelteradminprofile',
            name='specific_animal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
