# Generated by Django 6.0.1 on 2026-05-01 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen / Pet Owner'), ('veterinarian', 'Veterinary Doctor'), ('shelter_admin', 'Shelter Administrator'), ('civic_authority', 'Civic Authority'), ('agricultural_facility', 'Agricultural Facility'), ('admin', 'System Administrator')], default='citizen', max_length=30),
        ),
        migrations.CreateModel(
            name='AgriculturalFacilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('facility_address', models.TextField()),
                ('contact_person', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agricultural_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
