# Generated by Django 6.0.1 on 2026-05-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role_agriculturalfacilityprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen / Pet Owner'), ('veterinarian', 'Veterinary Doctor'), ('shelter_admin', 'Shelter Administrator'), ('civic_authority', 'Civic Authority'), ('admin', 'System Administrator')], default='citizen', max_length=30),
        ),
        migrations.DeleteModel(
            name='AgriculturalFacilityProfile',
        ),
    ]
