# Generated by Django 6.0.1 on 2026-05-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role_delete_agriculturalfacilityprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
