# Generated by Django 6.0.1 on 2026-04-15 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vital_signs', models.JSONField(blank=True, null=True)),
                ('consultation_notes', models.TextField(blank=True, null=True)),
                ('attending_vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_consultations', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='citizens.pet')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.URLField(max_length=500)),
                ('media_type', models.CharField(max_length=50)),
                ('diagnostic_tags', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='clinical.consultationlog')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medications', models.JSONField()),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('record_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinical.consultationlog')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=50)),
                ('date_administered', models.DateField(auto_now_add=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('record_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('is_amended', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='clinical.consultationlog')),
                ('original_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='clinical.vaccinationlog')),
            ],
        ),
    ]
