# Generated by Django 6.0.1 on 2026-06-06 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vital_signs', models.JSONField(blank=True, null=True)),
                ('consultation_notes', models.TextField(blank=True, null=True)),
                ('zoonotic_disease_flag', models.CharField(blank=True, help_text='Flags this record for Civic Authority Heatmaps', max_length=100, null=True)),
                ('health_status', models.CharField(blank=True, help_text="Updates the pet/livestock's health status", max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.TextField()),
                ('media_type', models.CharField(max_length=50)),
                ('diagnostic_tags', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medications', models.JSONField()),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('record_hash', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelfReportedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=50)),
                ('date_administered', models.DateField(auto_now_add=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('record_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('is_amended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('track', models.CharField(choices=[('puppy', 'Puppy Track'), ('kitten', 'Kitten Track'), ('cattle', 'Cattle Track'), ('small_ruminant', 'Small Ruminant Track'), ('poultry', 'Poultry Track'), ('equine', 'Equine Track'), ('custom', 'Custom Track')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('vaccine', 'Vaccine'), ('deworming', 'Deworming'), ('annual', 'Annual Booster'), ('seasonal', 'Seasonal Alert')], default='vaccine', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='citizens.livestock')),
            ],
        ),
    ]
