# Generated by Django 6.0.1 on 2026-06-06 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0002_initial'),
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'citizen'}, on_delete=django.db.models.deletion.CASCADE, related_name='owner_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='citizens.pet'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vet',
            field=models.ForeignKey(limit_choices_to={'role': 'veterinarian'}, on_delete=django.db.models.deletion.CASCADE, related_name='vet_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationlog',
            name='attending_vet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationlog',
            name='livestock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='citizens.livestock'),
        ),
        migrations.AddField(
            model_name='consultationlog',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='citizens.pet'),
        ),
        migrations.AddField(
            model_name='diagnosticmedia',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='clinical.consultationlog'),
        ),
        migrations.AddField(
            model_name='digitalprescription',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinical.consultationlog'),
        ),
        migrations.AddField(
            model_name='selfreportedrecord',
            name='livestock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_reports', to='citizens.livestock'),
        ),
        migrations.AddField(
            model_name='selfreportedrecord',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_reports', to='citizens.pet'),
        ),
        migrations.AddField(
            model_name='vaccinationlog',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='clinical.consultationlog'),
        ),
        migrations.AddField(
            model_name='vaccinationlog',
            name='original_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='clinical.vaccinationlog'),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='livestock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedules', to='citizens.livestock'),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedules', to='citizens.pet'),
        ),
        migrations.AddField(
            model_name='vaccinationscheduleitem',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.vaccinationschedule'),
        ),
    ]
