# Generated by Django 6.0.1 on 2026-06-06 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_appointments', models.PositiveIntegerField(default=5)),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('vet', models.ForeignKey(limit_choices_to={'role': 'veterinarian'}, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinical.appointmentslot'),
        ),
        migrations.CreateModel(
            name='VetScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10)),
                ('vet', models.ForeignKey(limit_choices_to={'role': 'veterinarian'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('vet', 'date')},
            },
        ),
    ]
