# Generated by Django 6.0.1 on 2026-04-21 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_alter_pet_media_url'),
        ('clinical', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfReportedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_reports', to='citizens.pet')),
            ],
        ),
    ]
