# Generated by Django 6.0.1 on 2026-06-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_appointmentslot_appointment_slot_vetscheduleday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinationlog',
            old_name='vaccine_name',
            new_name='injection_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='owner',
        ),
        migrations.AlterField(
            model_name='vaccinationscheduleitem',
            name='item_type',
            field=models.CharField(choices=[('injection', 'Injection'), ('deworming', 'Deworming'), ('annual', 'Annual Booster'), ('seasonal', 'Seasonal Alert')], default='injection', max_length=20),
        ),
    ]
