# Generated by Django 6.0.1 on 2026-04-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_selfreportedrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticmedia',
            name='media_url',
            field=models.TextField(),
        ),
    ]
