# Generated by Django 6.0.1 on 2026-06-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_rename_vaccine_name_vaccinationlog_injection_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetscheduleday',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='max_appointments',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='vetscheduleday',
            name='status',
            field=models.CharField(choices=[('holiday', 'Holiday')], default='holiday', max_length=10),
        ),
    ]
