# Generated by Django 6.0.1 on 2026-05-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_alter_diagnosticmedia_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationlog',
            name='zoonotic_disease_flag',
            field=models.CharField(blank=True, help_text='Flags this record for Civic Authority Heatmaps', max_length=100, null=True),
        ),
    ]
