# Generated by Django 6.0.1 on 2026-05-28 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0006_livestock_sosalert_alert_type'),
        ('clinical', '0005_consultationlog_zoonotic_disease_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('track', models.CharField(choices=[('puppy', 'Puppy Track'), ('kitten', 'Kitten Track'), ('cattle', 'Cattle Track'), ('small_ruminant', 'Small Ruminant Track'), ('poultry', 'Poultry Track'), ('equine', 'Equine Track'), ('custom', 'Custom Track')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedules', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedules', to='citizens.pet')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('vaccine', 'Vaccine'), ('deworming', 'Deworming'), ('annual', 'Annual Booster'), ('seasonal', 'Seasonal Alert')], default='vaccine', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.vaccinationschedule')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
    ]
