# Generated by Django 6.0.1 on 2026-04-07 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('behavioral_traits', models.TextField(blank=True)),
                ('medical_triage_status', models.CharField(max_length=50)),
                ('intake_date', models.DateField(auto_now_add=True)),
                ('found_location', models.CharField(blank=True, max_length=255)),
                ('kennel_zone_id', models.CharField(max_length=50)),
                ('is_adopted', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('media_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(limit_choices_to={'role': 'citizen'}, on_delete=django.db.models.deletion.CASCADE, related_name='adoption_applications', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='shelter.animalinventory')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('admin', models.OneToOneField(limit_choices_to={'role': 'shelter_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='authorized_shelter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='animalinventory',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='shelter.shelter'),
        ),
    ]
