# Generated by Django 6.0.1 on 2026-06-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('behavioral_traits', models.TextField(blank=True)),
                ('medical_triage_status', models.CharField(max_length=50)),
                ('intake_date', models.DateField(auto_now_add=True)),
                ('found_location', models.CharField(blank=True, max_length=255)),
                ('kennel_zone_id', models.CharField(max_length=50)),
                ('is_adopted', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('listing_type', models.CharField(choices=[('Adopt', 'Adopt'), ('Sell', 'Sell'), ('Donate', 'Donate')], default='Adopt', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('media_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
