# Generated by Django 6.0.1 on 2026-06-06 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant',
            field=models.ForeignKey(limit_choices_to={'role': 'citizen'}, on_delete=django.db.models.deletion.CASCADE, related_name='adoption_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='shelter.animalinventory'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='admin',
            field=models.OneToOneField(limit_choices_to={'role': 'shelter_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='authorized_shelter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalinventory',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='shelter.shelter'),
        ),
    ]
