# Generated by Django 6.0.1 on 2026-06-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Approved', 'Approved'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
