# Generated by Django 6.0.1 on 2026-04-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_alter_adoptionapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalinventory',
            name='listing_type',
            field=models.CharField(choices=[('Adopt', 'Adopt'), ('Sell', 'Sell'), ('Donate', 'Donate')], default='Adopt', max_length=20),
        ),
        migrations.AddField(
            model_name='animalinventory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='animalinventory',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
