# Generated by Django 6.0.1 on 2026-05-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_animalinventory_listing_type_animalinventory_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalinventory',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
