# Generated by Django 6.0.1 on 2026-05-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_animalinventory_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
